### ISSUE TITLE
IE console error when using this one.

### ISSUE THREAD

**Issue by QBTomzhu** [gund/ng-http-interceptor#124]
Chrome works fine

but for IE 11, if I inject http module and this one, the error in console is

```javascript
EXCEPTION: 'Proxy' is undefined
```

the code in App.component is very simple

```ES6

constructor(private http: Http,
    private httpInterceptor: HttpInterceptorService
  ) {
}

```

**Comment by gund** [comment]
Please make sure to read Readme.md:
`This library uses Proxy from ES6 spec so if you need to support browsers that are ES5 compatible include proxy-polyfill.`

Install this library: https://github.com/GoogleChrome/proxy-polyfill

**Comment by QBTomzhu** [comment]
Sorry, thanks for the replay
