### ISSUE TITLE
[Question] How to test with InjectableHttp

### ISSUE THREAD

**Issue by GregOnNet** [gund/ng-http-interceptor#125]
Hey all,

first a big thanks for providing ng-http-interceptor.
It has a really nice and easy to understand API. :heart: 

I want to test if my interceptions work as expected writing unit test.
Can you please provide some information how I have to override `Http` in my TestBed configuration?

```typescript
describe('When a http request timeout occurs', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [
        HttpModule,
        HttpInterceptorModule
       ],
     providers: [{
       provide: Http,
       useFactory: (mockBackend, options) => {
         /*
           * What do I have to do to override Http the right way?
           */
           return new Http(mockBackend, options);
         },
         deps: [MockBackend, BaseRequestOptions]
       }]
    });
});
```

Many thanks in advance
Greg

**Comment by gund** [comment]
Hi Greg, thanks for the question.

Well I guess the simplest way you can test it is just by importing `HttpModule` and `HttpInterceptorModule`.
So you basically do not need to add any providers at all, you can just register a Spy as an interceptor function and assert that it was called in your test suits.

Something like that:
```ts
describe('When a http request timeout occurs', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [
        HttpModule,
        HttpInterceptorModule
       ],
     providers: [] // <-- No providers here
    });
  });

  it('should call interceptor on request', inject([Http, HttpInterceptor], (http, httpInterceptor) => {
    // Setup and register interceptor function
    const interceptorSpy = jasmine.createSpy('interceptorSpy')
      .and.callFake(data => data); // <-- If you want your request to complete
                                   //   - return data back from interceptor function
    httpInterceptor.request().addInterceptor(interceptorSpy);

    // Make a request
    http.get('/whatever').subscribe();

    // Assert that interceptor function was called
    expect(interceptorSpy).toHaveBeenCalledWith(['/whatever']);
  });
});
```

And of course you can setup and register your interceptor function `beforeEach` so that will cleanup your test suits if you have a lot of them =)

Hope that helps,
Alex

**Comment by GregOnNet** [comment]
Hey Alex thanks for the quick response. :+1: 
I think I did not explain my use case the right way, sorry.

I use [auth0/angular-jwt](https://github.com/auth0/angular2-jwt) in my application.
That's why my Services depend on `AuthHttp` rather than `Http`.
To mock my Http Requests I have to provide the `Http` service with `MockBackend`.
Than I am able to inject AuthHttp into my Service.

I think using `HttpInterceptorModule` in my test takes no effect because the factory method for `Http` overrides the changes.
That's why I ask for a way to provide the intercepted HTTP service with `useFactory`.

Here is the full configuration of my TestBed.
>Please tell me if you need a working example.
>Than I will create an isolated example.

```typescript
describe('When a http request timeout occurs', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [
        HttpModule,
        HttpInterceptorModule
       ],
      providers: [{
        provide: Http,
        useFactory: (mockBackend, options) => {
          /*
            * What do I have to do to override Http the right way?
            */
            return new Http(mockBackend, options);
          },
          deps: [MockBackend, BaseRequestOptions]
        }, {
          provide: AuthHttp,
          useFactory: (authConfig = {} as AuthConfig, http: Http) => {
                               return new AuthHttp(authConfig, http);
           },
           deps: [AuthConfig, Http]
         }, {
           provide: AuthConfig,
             useFactory: () => new AuthConfig({
               tokenGetter: () => 'fakedToken'
             })
        },
        MockBackend,
        BaseRequestOptions,
        HttpErrorNotifier // Service setting up Interceptions
        MyService // Service making API-Call triggering Interception
      ]
    });
});
```

Once again, thank you.

**Comment by gund** [comment]
Okay, so if understand this right you only want to provide `MockBackend` as `XHRBackend`.
If so, you really do not need to touch `Http` but just `XHRBackend`:
```ts
providers: [
  {provide: XHRBackend, useClass: MockBackend}
]
```

And that will essentially replace everything withing Http internally.
And then it's important to retrieve `MockBackend` in tests from `XHRBackend` like so:
```ts
it('should ...', inject([XHRBackend], mockBackend => {
  // mockBackend is of type MockBackend because you provided it
}));
```

**Comment by GregOnNet** [comment]
Hi,

sorry for the late response.
Your answer is totally right. :+1: 

I thank you very much for helping me.

Sunny Regards from Leipzig, Germany
Greg
