### ISSUE TITLE
main in package.json should point to umd bundle

### ISSUE THREAD

**Issue by Necroskillz** [gund/ng-http-interceptor#128]
See how it is in angular: https://github.com/angular/angular/blob/master/modules/%40angular/core/package.json

`main` in package.json should point to the bundle, while new property `module` should point to es6 style `index.js`.

**Comment by gund** [comment]
Hey thanks for pointing this out, will update package.json accordingly

**Comment by gund** [comment]
BTW: Do you know if this change may bring potential breaking change in behavior or bundling process?

**Comment by Necroskillz** [comment]
I know it breaks with some tools as it is now :P (for example `karma-typescript`. But it should be like that since angular also has it like that.

**Comment by gund** [comment]
Yeah, so this change can be included only in version 3 which is in beta now, until angular 4 itself will come out from beta =)

**Comment by Necroskillz** [comment]
Not sure if u understood: currently the `main` pointing to es6 module does not work with `karma-typescript` (while `main` pointing to umd bundle and `module` pointing to es6 module does). It also works with webpack and rollup. I think this can be done sooner.

**Comment by gund** [comment]
Oh you mean it is breaking in current configuration with `karma-typescript`?
I thought it might break if I will change config as you suggested =)
So it is safe to update config without breaking change?

**Comment by Necroskillz** [comment]
As far as I know it should be safe. Not 100% sure.

I'm switching to `karma-webpack` now because `karma-typescript` also has some other issues. So I'm not in a hurry for this.

**Comment by gund** [comment]
Okay, then I will locally update config and try on test webpack project to check if basic usage won't break and then release as a fix. Otherwise it will be a breaking change.

Will update here here soon.

**Comment by gund** [comment]
Well I tried locally to use lib with updated package.json and seems like it is working just fine so I will release and update soon.
