### ISSUE TITLE
intercept errors

### ISSUE THREAD

**Issue by joshikeerti** [gund/ng-http-interceptor#134]
Is there a way to intercept errors? Currently  httpInterceptor.request() and httpInterceptor.response() intercept the request and response, but if we need to intercept errors, is there a method that can help do this?

**Comment by gund** [comment]
How about `catch()` operator?
```ts
httpInterceptorService.response().addInterceptor(res => res.catch(e => {
  console.log('Caught http error:' + e);
  return Observable.empty(); // Recover from error
}));
```

**Comment by gund** [comment]
I'm going to close this assuming my example helped you.
