### ISSUE TITLE
Cannot read property 'Observable' of undefinedInterceptableStoreFactory.createStore,: __extends is not defined

### ISSUE THREAD

**Issue by RobertRajcool** [gund/ng-http-interceptor#136]

**Comment by gund** [comment]
Please provide repo or plunker which reproduces the problem

**Comment by zxshinxz** [comment]
I was facing the same issue and I found this issue from other libaray facing same issue: https://github.com/akveo/ng2-smart-table/issues/26

for quick fix, you can change 

tsconfig.aot.json of ng-http-interceptor to following and rebuild

```
{
  "compilerOptions": {
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noEmitHelpers": false,             //     "noEmitHelpers": true,   --->     "noEmitHelpers": false,
    "lib": ["es6", "dom"],
    "module": "es2015",
    "moduleResolution": "node",
    "outDir": "./dist",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "./node_modules/@types"
    ]
  },
  "files": [
    "src/index.ts"
  ],
  "angularCompilerOptions": {
    "genDir": "compiled"
  }
}

```

but, I'm pretty sure there's better way than this.

BTW Thank you for great library :)

**Comment by gund** [comment]
Hey @zxshinxz thanks for response.

Actually have you tried to include `ts-helpers` module in your application?
Because I'm also using this library in other projects and do not face this issue in none of them.

**Comment by zxshinxz** [comment]
@gund your right

it was in the README all along! and it works like a charm
Thank you for pointing it out :)

**Comment by gund** [comment]
Cool, thanks for confirming =)
