### ISSUE TITLE
How can we Register interceptors globally ??

### ISSUE THREAD

**Issue by teswar** [gund/ng-http-interceptor#137]

**Comment by gund** [comment]
Did you go through the example use case?
You can set interceptors that way from any component or service you want.

**Comment by teswar** [comment]
Yes, did go through this [example ](https://github.com/gund/ng-http-interceptor#example-use-case), but there you are adding/removing interceptors probably in a service level.
I think it would be better to configure the interceptors in the module level, while the **HttpInterceptorService** is being injected.  As you have stated in your [concept](https://gist.github.com/gund/1072056dd3af86f084ae3a111946415b#edit) or [as here](https://github.com/voliva/angular2-interceptors#set-up-interceptorservice)

**Comment by gund** [comment]
The thing is services should always remain as singletons meaning they are only of one instance no matter where you are injecting it (any component or service).

That said all registered interceptors always global.

**Comment by teswar** [comment]
I understand the singleton concept. 
In my project there a independent service to each resources, where **HttpInterceptorService** is being injected via constructor and most of the API calls need OAuth Token attached. 
The problem is I can't be certain which service will always be firstly created, so that the interceptors can be configured in that service.
Else I have to configure in the base-service, which is inherited by all my resource-services.

But I am able to do this in the main app's module level. I will not have to be worried about these rite ?

**Comment by gund** [comment]
I'm sure you can do that from main app.

However I'm not sure I can see the problem why you ever should be worried about services construction order?
Can you please provide some example use case?

**Comment by gund** [comment]
I'm going to close this assuming your issue was resolved

**Comment by teswar** [comment]
Yeap. Thnx...
