### ISSUE TITLE
version 2.0.3 leads to duplicated requests

### ISSUE THREAD

**Issue by ujibang** [gund/ng-http-interceptor#138]
we use ng-http-interceptor to inject authentication headers and handle some http errors (such as 401 and 403)

we updated to 2.0.3 and noticed that some calls are duplicated. for instance our feature "create new stuff" leads to have 2 new rows in the db or "delete stuff" generates two DELETE calls.

downgrading to 2.0.2 fixed the issue.

ng http uses cold observables, so we wonder if 2.0.3 somehow subscribe to calls leading to this critical problem.

**Comment by ujibang** [comment]
I created a plunker that reproduces the issue: http://plnkr.co/edit/nODcfegVK6iXtRNgrAy6?p=preview

the plunker shows two buttons "load data" and "delete" that send GET and DELETE request tot he demo instance of RESTHeart at dbapi.io/db/coll. 

loading data works fine but DELETE request gets executed twice.

The problem arises when I added the response interceptor (the request interceptor does not have this issue):

```
httpInterceptor.response().addInterceptor((res, method) => {
        res.subscribe(console.log('http response intercepted')); 
        
        return res;
      });
```

res.subscribe clearly leads to this issue if the res is a cold observable....

**Comment by gund** [comment]
Sure, `.subscribe()` will lead you to one more request.
What you want to do probably is this:
```ts
httpInterceptor.response().addInterceptor((res, method) => {
        return res.do(() => console.log('http response intercepted'));
      });
```

**Comment by ujibang** [comment]
tried and got

`EXCEPTION: Error in ./App class App - inline template:6:9 caused by: res.do is not a function`

**Comment by gund** [comment]
Sure thing, you need to import that operator:
```ts
import "rxjs/add/observable/do"
```

**Comment by ujibang** [comment]
yep `import "rxjs/add/operator/do"` worked!

given that 2.0.2 and 2.0.3 manage observable in that different way, I suggest you to add a note on the README about that. 

Thanks and congrats for your work!

**Comment by gund** [comment]
Thank you!

Actually it is the way library supposed to work in the beginning (not converting observables from "cold" to "hot") but since I was not able to get rid of duplicate requests I was forced to do that sharing.

So now it's like a natural way of working with observables as you would work with them without this library =)
I'm not sure if I was mentioning that this library was sharing observables but since 2.0.3 it's not doing it - so should not bring any confusion any more =)
