### ISSUE TITLE
angular-cli project w/TS 2.1 and I'm still seeing `ReferenceError: __extends is not defined`

### ISSUE THREAD

**Issue by uberspeck** [gund/ng-http-interceptor#139]
I'm still seeing the `ReferenceError: __extends is not defined` error. The project was generated using `@angular/cli@1.0.0-rc.2` which includes TS2.1. [According to the ts-helpers library](https://github.com/ngParty/ts-helpers#note-starting-typescript-21-this-package-wont-be-needed-anymore) it's not needed for TS>=2.1. I've tried both with and without the ts-helpers lib and i see the error either way. Anything I'm missing?

**Comment by gund** [comment]
In order to use ts-lib you need to use rc version of this library which you can install via npm @beta tag.
Then just add `importHelpers: true` in your tsconfig.json

**Comment by uberspeck** [comment]
Thanks @gund! That fixed the error. However, the interceptors never seem to execute. I have the following in my `AppModule` and nothing is logged to the console...

```typescript
export class AppModule {
  constructor(
    httpInterceptor: HttpInterceptorService
  ) {
    httpInterceptor.request().addInterceptor( (data, method) => {
      console.log(method, data);
      return data;
    });
    httpInterceptor.response().addInterceptor( (res, method) => {
      res.do( r => console.log(method, r) );
      return res;
    });
  }
}
```

**Comment by gund** [comment]
Glad you solved issue.
Regarding your question - you should always return modified observable because operators do not mutate original one they are creating new ones.

**Comment by uberspeck** [comment]
Thanks for the quick response! I'm not sure I understand. Could you provide an example? FWIW, my goal is to retrieve JWT tokens from responses, and add tokens to requests...

**Comment by gund** [comment]
Sure, you need to directly return new observable with operators you want to apply:
```ts
    httpInterceptor.response().addInterceptor( (res, method) => {
      return res.do( r => console.log(method, r) );
    });
```

**Comment by uberspeck** [comment]
Ugh. I'm still having trouble. I'm not sure what I'm missing? Here's what I have so far...

```typescript
/**
 * Send JWT
 */
this.httpInterceptor.request().addInterceptor( (data, method) => {
  let token = this.jwtService.token;
  let {options, idx} = getHttpOptionsAndIdx(data, method);
  if (!options.headers) {
    options.headers = new Headers();
  }
  // Add JWT to request
  options.headers.append('Authorization', `Bearer ${token}`);
  data[idx] = options;
  console.log(JSON.stringify(data));
  return data;
});

/**
 * Capture JWT
 */
this.httpInterceptor.response().addInterceptor( (res, method) => {
  return res.do( (_res) => {
    this.jwtService.cacheToken(_res.json().jwt);
  });
});
```
The console logs the new data as expected...

```json
["/",{"method":null,"headers":{"Authorization":["Bearer eyJ0eXAiOi..."]},"body":null,"url":null,"withCredentials":null,"responseType":null}]
```
But the request doesn't include the `Authorization` token I just appended??

<img width="356" alt="screen shot 2017-03-17 at 11 06 54 am" src="https://cloud.githubusercontent.com/assets/857256/24054830/5a138e1c-0b03-11e7-9979-58fe08f25639.png">

Thank you for your patience!

**Comment by uberspeck** [comment]
Ok, I think I found the source of the problem. We're using the `apollo-angular` lib with resolvers. I *think* the interceptors aren't being applied because we're not subscribing to get the data, it's passed in the `route.snapshot.data`

**Comment by gund** [comment]
But that library should internally somewhere subscribe to http observable triggering interceptors right?

**Comment by uberspeck** [comment]
Well, after all of that, it looks like the Apollo client doesn't even use the angular http client. That was frustrating. Anyway, thanks for your patience and a great library! I'll probably use it on my next project :)
