### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by yasiryc** [gund/ng-http-interceptor#142]
I install the latest version from NPM and getting following error on ng serve

Angular version - 4.0.1
Typescripit - 2.2.1

ERROR in ./~/ng-http-interceptor/dist/http/interceptable-http.js
Module not found: Error: Can't resolve 'tslib' in 'C:\source\Angular\client\node_modules\ng-http-interceptor\dist\http'
 @ ./~/ng-http-interceptor/dist/http/interceptable-http.js 1:0-33
 @ ./~/ng-http-interceptor/dist/http/index.js
 @ ./~/ng-http-interceptor/dist/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

**Comment by gund** [comment]
Please install npm module `tslib` and add to your tsconfig file `importHelpers: true`

**Comment by yasiryc** [comment]
Thanks for the feedback. I initially thought i had tslib installed which i did but was missing tsconfig setting. 

I have created the interceptor as seperate service and register it to app module but not able to intercept any requests. 

Any ideas what i might be missing here..

**Comment by gund** [comment]
Did you import the module itself into the root module?

**Comment by yasiryc** [comment]
Yes i did. I import module from ng-http-interceptor 

import { HttpInterceptorModule  } from 'ng-http-interceptor';

Also i registered custom interceptor service as provider in the root module. Here is code from custom interceptor service
`import { Injectable } from '@angular/core';
import { HttpInterceptorService } from 'ng-http-interceptor';

@Injectable()
export class HttpcustominterceptorService {

  constructor(private _httpInterceptor: HttpInterceptorService) {
    _httpInterceptor.request().addInterceptor((data, method) => {
      console.log("Inside Interceptor Request");
      console.log(method, data);
      return data;
    });

    _httpInterceptor.response().addInterceptor((res, method) => {
      console.log("Inside Interceptor response");
      return res.do(r => console.log(method, r));
    });
  }

}
`
`

**Comment by gund** [comment]
That looks right and should work fine.
Can you create a plunkr with your problem so I can verify it?

**Comment by gund** [comment]
Will close this one since too long.
If you still have an issue - feel free to reopen.
