### ISSUE TITLE
[Question] How to add default headers for every http call?

### ISSUE THREAD

**Issue by BenevidesLecontes** [gund/ng-http-interceptor#145]
Hi! Sorry for asking here, how can i add default headers with this interceptor? Thanks

**Comment by gund** [comment]
If you will follow readme you can find there an example:
```ts
httpInterceptor.request().addInterceptor((data, method) => {
  const headers = getHttpHeadersOrInit(data, method);
  headers.set('X-Custom-Header', 'value');
  return data;
});
```

Also if your headers are static you can do that by providing BasicRequestOptions from @angular/http in providers

**Comment by gund** [comment]
I will close this issue as it is answered.
If you have any questions please feel free to open a new issue.
