### ISSUE TITLE
Show an example of response interceptors with forkJoin observable

### ISSUE THREAD

**Issue by alejandro-heredia-coderoad-com** [gund/ng-http-interceptor#148]
Could you please show an example of response interceptors with **forkJoin observable** I'm not able to make it work.

**Comment by gund** [comment]
That should be as simple as:
```ts
httpInterceptor.response().addInterceptor(res =>
  res.forkJoin(Observable.of('test').delay(1000)));
```
So if request will end faster that 1s, it will emit exactly after 1s with response and 'test'.
If request will be longer then 1s it will emit right after response arrives but in reverse order: first 'test' and then response.

**Comment by gund** [comment]
I'm going to close this issue.
If you have any other questions please feel free to open new issue.
