### ISSUE TITLE
Get headers on response

### ISSUE THREAD

**Issue by alperg** [gund/ng-http-interceptor#149]
I set my headers on request, and works fine, but I also would like to get the headers on every response, but couldn't figure it out.

Here is my request interceptor:
```js
this.httpInterceptor.request().addInterceptor((data, method) => {
  const headers = getHttpHeadersOrInit(data, method);
  if (this.SESSION_COOKIE) {
    headers.set('header1', this.SESSION_COOKIE);
  }
  return data;
});
```

I need to get the SESSION_COOKIE on every response. Could you please post an example?

**Comment by gund** [comment]
It is as easy as:
```ts
this.httpInterceptor.response().addInterceptor(res =>
  res.do(r => console.log(r.headers)));
```
