### ISSUE TITLE
Don't require RxJS version higher than what Angular requires

### ISSUE THREAD

**Issue by imgx64** [gund/ng-http-interceptor#153]
This is a minor nitpick, but this project requires RxJS ^5.3.0 while [Angular requires ^5.0.1](https://github.com/angular/angular/blob/master/package.json#L26). So unless you're using some feature of RxJS >5.0.1, I suggest you require the same version.

**Comment by gund** [comment]
Sure, you totally right.
I will downgrade all the peer dependencies to the major version, to not to cause any conflicts.

**Comment by gund** [comment]
This is fixed and merged.
Because this is chore change - it will land with next release.
