### ISSUE TITLE
How to handle http request cancellation in http-interceptor

### ISSUE THREAD

**Issue by gopinathshiva** [gund/ng-http-interceptor#156]
Hi I would like to know, how to handle cancellation of http request using ng-http-interceptor.

My current code.
        `httpInterceptor.request().addInterceptor((data, method) => {
          this.requestCount += 1;
          if(!this.requestLoader){
             this.requestLoader = true;
          }
          return data;
       });

    httpInterceptor.response().addInterceptor((res, method) => {
      console.log(res,method);
      return res.timeoutWith(
          AppConstants.httpTimeout,
          Observable.defer(() => {
            this.decrementRequestCount();
            return Observable.throw(new Error("Request Timeout"))
          }
        )
      ).do((data) => {
        // console.log(method,data);
        this.decrementRequestCount();
      }, (error) => {
        this.decrementRequestCount();
        console.log("Http Error : "+ error);
      })

    });`

Here I am incrementing and decrementing the request , based on the request and response respectively. But when the request is cancelled, I am unable to handle it. Any help is appreciated

**Comment by gopinathshiva** [comment]
Using finally helps the above situation. But any improved answer for the above issue is appreciated. 
`httpInterceptor.response().addInterceptor((res, method) => {
      return res.timeoutWith(
          AppConstants.httpTimeout,
          Observable.defer(() => {
            this.decrementRequestCount();
            return Observable.throw(new Error("Request Timeout"))
          }
        )
      ).do((data) => {
        console.log(method,data);
      }, (error) => {
        console.log("Http Error : "+ error);
      }).finally(() => {
        this.decrementRequestCount();
      });

    });
`

**Comment by gund** [comment]
I think solution with `finally` operator is good.
I have only one concern about decrementing requests, your finally operator will be called in any way either it's success or error of the http observable, but you also decrementing it in the `timeoutWith` operator and throwing  error down the chain so `finally` also will be triggered and you will end up with 2 decrements per 1 request...
I guess you need to decrement requests only in `finally` operator.

**Comment by gopinathshiva** [comment]
oh yeah fixed it. Really appreciate that.
