### ISSUE TITLE
IE11 Shims/Polyfills issue

### ISSUE THREAD

**Issue by oldtimeguitarguy** [gund/ng-http-interceptor#159]
I was having a weird issue with Angular 4.2.6 on IE11... it was as if none of the polyfills were being recognized by the browser. As a result, the site completely broke and would not load. Errors in the console mentioned things like "Proxy" doesn't exist and "assign" is not a valid Object property... all things that the polyfills take care of...

I spent hours on this until, after a process of elimination in my code, I removed ng-http-interceptor. Suddenly, the site is working again.

**Comment by oldtimeguitarguy** [comment]
I see in the documentation that you recommend Google Chrome's `proxy-polyfill`. I thought I would give this another try, as I tried it before, but not since I updated everything else and figured out that this plugin was causing the issue.

So I installed that and I'm importing it under "Application Imports" in `polyfills.ts`. However, now I'm stuck with the other issue I mentioned - other shims aren't working.

With that imported, it is no longer recognizing tics (for concatinated strings) and Object.assign

**Comment by gund** [comment]
How do you include this polyfill, as TS file or JS file?

It should be included as TS file so that it can be transpiled down do ES5.

Also make sure you import it aster ass your primary polifills like core-js for ES6 features.

**Comment by oldtimeguitarguy** [comment]
You know what - I was importing the base package, which - according to `package.json` - is a `.js` file... and looking in the codebase, I only see `.js` files... hmmm...

**Comment by gund** [comment]
If you are talking about this library than yes it should be .js file as it is already precompiled.
What I was talking about above is actually the proxy polyfill - that should not be a .js file but .ts file.

**Comment by rkatipally** [comment]
@gund I have the same issue. I followed the link that is included in the documentation, the url for proxy is https://github.com/GoogleChrome/proxy-polyfill. This one only has .js file for proxy. Can you please point me to corresponding .ts file. Thank you.

**Comment by gund** [comment]
@rkatipally what you need to do basically is just rename the file to have `.ts` extension and make sure you have removed `use strict` statement from the file.

That should be enough.

**Comment by Newan** [comment]
Is it possible to add this polyfill to a polyfill.ts from an angular (Version 4.x) project?

**Comment by gund** [comment]
You can easily import it into your `polyfill.ts` file.

**Comment by Newan** [comment]
ok, I have an angular 4.1.3 project:

`npm install proxy-polyfill --save`

my polyfill.ts:
```
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';
import 'classlist.js';
import 'web-animations-js';  
import 'zone.js/dist/zone'; 
import 'proxy-polyfill'
```

ng serve on an IE 11
```
SCRIPT1014: Invalid character
polyfills.bundle.js (5997,29)
```


Edit:
It seems like this issues, but I do not know how to import the min version into the polyfill file?
https://github.com/GoogleChrome/proxy-polyfill/issues/24

**Comment by gund** [comment]
Closed due to inactivity.
