### ISSUE TITLE
Property 'do' does not exist on type 'Observable<Response>'.

### ISSUE THREAD

**Issue by raykin** [gund/ng-http-interceptor#163]
I follow the example code on ionic2 projection.
The request interceptor works but response interceptor failed.
I looks an API change bug.
Here is my libs env.
```
~/studio/aska (master ✘)✹✭ ᐅ npm list rxjs
Deltux@0.0.0 /Users/raykin/studio/aska
└── rxjs@5.4.0
~/studio/aska (master ✘)✹✭ ᐅ npm list @angular/core
Deltux@0.0.0 /Users/raykin/studio/aska
└── @angular/core@4.1.3
```

**Comment by gund** [comment]
If you are using RxJs operators you need to import them:
```ts
import 'rxjs/add/operator/do';
```

**Comment by raykin** [comment]
@gund sorry for the dumb question. it works. thanks. I've just upgrade from angularjs to angular, need more time to research on rxjs
