### ISSUE TITLE
Response interceptor is not called on error

### ISSUE THREAD

**Issue by creever** [gund/ng-http-interceptor#164]
Hi!

I try to catch error response but its not working. It was a bug earlier #21, maybe its a bug again?
I have ng-http-interceptor@3.1.2 version.

The console log called only on success response but its not when the status code is 500 for instance.
```
httpInterceptor.response().addInterceptor(res => {
      return res.do(r => {
        console.log("Status: ", r.status);
      });
    });
```

**Comment by gund** [comment]
In your code snippet I cannot see catch operator, maybe that is why you are missing errors?

**Comment by zeqk** [comment]
I have the same error:

```
httpInterceptor.response().addInterceptor((res, method) => {
      try {
        return res.do(r => {
          try {
            console.log(method, r)
          }
          catch(ex){
            console.log("catcth 2", ex);
          }
          
        });
      }
      catch(ex) {
        console.log("error catch 1", ex);
      }
    });
```

 only on success response is working

**Comment by gund** [comment]
What I meant by catch operator is not language try/catch construct but RxJs Observable .catch operator (like .do)

```ts
httpInterceptor.response().addInterceptor(res => {
      return res
        .do(r => doSideEffectsOnSuccess(r))
        .catch(e => handleErrorAndReturnNewObservable(e));
    });
```

For further details about catch operator usage please refer to RxJs [catch documentation](https://github.com/ReactiveX/rxjs/blob/master/spec/operators/catch-spec.ts).

**Comment by dsge** [comment]
You can also use the second parameter of `do()`:
```js
httpInterceptor.response().addInterceptor(res => {
    return res.do(
      r => {
        console.log("Status: ", r.status);
      }, 
      err => {
        console.log("Error");
      }
    );
});
```
The first parameter can be replaced with `null`:
```js
httpInterceptor.response().addInterceptor(res => {
    return res.do(
      null, 
      err => {
        console.log("Error");
      }
    );
});
```

**Comment by zeqk** [comment]
@gund @dsge Thanks!

**Comment by gund** [comment]
Awesome! Will close this issue then =)
