### ISSUE TITLE
Intercept header parameters at app run

### ISSUE THREAD

**Issue by sandroverna** [gund/ng-http-interceptor#166]
hi @gund
use angular 4 and I have this problem:
between the proxy and my application I have a layer of Identity and Access Management, this layer after the auth operation append the user's identity information in the Request Headers parameters and call my application root page "/"
my problem is to be able to read the Request Headers parameters at the start of the application.
angular 4 I'm trying to see if your interceptor can fix me.
do you have any advice on this?

**Comment by gund** [comment]
Hi @sandroverna I don't really understand the question.
Can you please show an example of what you want to achieve?

**Comment by gund** [comment]
Closed due to inactivity.
