### ISSUE TITLE
Interceptor getting called only in preflight request not in subsequent call

### ISSUE THREAD

**Issue by vishalmote** [gund/ng-http-interceptor#168]
As, latest browser do a preflight request on each request. But this plugin interceptor is getting called at the time of preflight not at the time of actual request. can you please look into the issue and update asap.

**Comment by gund** [comment]
This is how CORS requests are handled basically.
Your code does not initiate separate preflight request but only one and then browser does preflight if needed.
So interception always happens for the original request and no interception happens for preflight requests.
You simply cannot even track them via JS and handle them.

**Comment by vishalmote** [comment]
Hello Gund,

Thanks for the revert, I have found the solution for the above thing. But problem with the solution is that,
Following code is allowing me to do operation on response of preflight as well as actual request.
```
httpInterceptor.response().addInterceptor((res, method) => {
      return res.do(r => {
        this.errorLogger(r);
        this.stopLoader(r);
      });
    });
```
But when I try to use the above solution as example given in your documentation, I get the following error.

> vendor.bundle.js:67427 ERROR Error: Uncaught (in promise): TypeError: res.do is not a function
> TypeError: res.do is not a function

So I Modified code to the following,

```
httpInterceptor.response().addInterceptor((res, method) => {
      this.responseLogger(res);
      this.stopLoader(res);
      return res;
    });
```
This above change is not getting triggered on actual request rather getting triggered on preflight.

Problem is that why code given in your example is throwing a res.do is function error. If you have any idea on this, can you revert please. Did I missed something while doing installation??

**Comment by gund** [comment]
Regarding do error check this issue https://github.com/gund/ng-http-interceptor/issues/158

**Comment by vishalmote** [comment]
Thanks It worked!
